//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activos_Fijos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activos_Fijos()
        {
            this.Calculo_Depreciacion = new HashSet<Calculo_Depreciacion>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int Departamento { get; set; }
        public int Tipos_Activos { get; set; }
        public System.DateTime Fecha_Registro { get; set; }
        public int Valor_Compra { get; set; }
        public decimal Depreciacion_Acumulada { get; set; }
        public bool Desechado { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<int> Monto_Despreciado { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Tipos_Activos Tipos_Activos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calculo_Depreciacion> Calculo_Depreciacion { get; set; }
    }
}
