//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Activos_FijoEntities : DbContext
    {
        public Activos_FijoEntities()
            : base("name=Activos_FijoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activos_Fijos> Activos_Fijos { get; set; }
        public virtual DbSet<Calculo_Depreciacion> Calculo_Depreciacion { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Tipo_Persona> Tipo_Persona { get; set; }
        public virtual DbSet<Tipos_Activos> Tipos_Activos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
    }
}
