//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculo_Depreciacion
    {
        public int ID { get; set; }
        public System.DateTime Periodo { get; set; }
        public int Activo_Fijo { get; set; }
        public int ID_AsientosCont { get; set; }
        public System.DateTime Fecha_Proceso { get; set; }
        public int Monto_Despreciado { get; set; }
        public decimal Depreciacion_Acum { get; set; }
        public int Cuenta_Compra { get; set; }
        public int Cuenta_Despreciacion { get; set; }
        public bool Desechado { get; set; }
    
        public virtual Activos_Fijos Activos_Fijos { get; set; }
    }
}
