//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public int Departamento { get; set; }
        public int Tipo_Persona { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public bool Estado { get; set; }
        public bool Desechado { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Tipo_Persona Tipo_Persona1 { get; set; }
    }
}
