//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public int Departamento { get; set; }
        public int Tipo_Persona { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public bool Estado { get; set; }
        public bool Desechado { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Tipo_Persona Tipo_Persona1 { get; set; }
    }
}
