//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_Activos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipos_Activos()
        {
            this.Activos_Fijos = new HashSet<Activos_Fijos>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int Contable_Compra { get; set; }
        public int Contable_Depreciacion { get; set; }
        public bool Estado { get; set; }
        public bool Desechado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activos_Fijos> Activos_Fijos { get; set; }
    }
}
