//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivosFijo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos_Activos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipos_Activos()
        {
            this.Activos_Fijos = new HashSet<Activos_Fijos>();
        }
    
        public int ID { get; set; }
        public string Descripcion { get; set; }
        public int Contable_Compra { get; set; }
        public int Contable_Depreciacion { get; set; }
        public bool Estado { get; set; }
        public bool Desechado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activos_Fijos> Activos_Fijos { get; set; }
    }
}
